management:
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always
  endpoints:
      web:
        exposure:
          include: "*"
server:
  port: 8010
spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: microservice-consumer-feign-with-hystrix

eureka:
  client:
    service-url:
        # 指定eureka server通信地址，注意/eureka/小尾巴不能少
#      defaultZone: http://10.254.193.30:9001/eureka/,http://10.254.193.31:9002/eureka/,http://10.254.193.32:9003/eureka/
      defaultZone: http://localhost:8888/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
#    hostname: 10.254.193.129

feign:
  hystrix:
    enabled: true
