server:
  port: 8020
spring:
  application:
    # 指定注册到nacos server上的服务名称
    name: microservice-consumer
  cloud:
    nacos:
      discovery:
        ip: 127.0.0.1
        server-addr: 127.0.0.1:8848
        log-name:

# https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-discovery
management:
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always
  endpoints:
      web:
        exposure:
          include: "*"

