server:
  port: 9000

spring:
  application:
    name: spring-cloud-alibaba-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&autoReconnect=true
    username: root
    password: root
    hikari:
      auto-commit: true
      maximum-pool-size: 100
      max-lifetime: 1800000
      minimum-idle: 5
      idle-timeout: 300000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
        port: 8721
      eager: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: redis123
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  cache:
    type: redis
    redis:
      time-to-live: 600000   # 10分钟过期
      cache-null-values: true # 缓存空值防穿透
      key-prefix: "sca:"     # key 前缀

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.cicoding.model

logging:
  level:
    root: info
    cn.cicoding: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
