server:
  port: 9000

spring:
  application:
    name: spring-cloud-alibaba-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&autoReconnect=true
    username: root
    password: root
    hikari:
      auto-commit: true
      maximum-pool-size: 100
      max-lifetime: 1800000
      minimum-idle: 5
      idle-timeout: 300000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.cicoding.model

logging:
  level:
    root: info
    cn.cicoding: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
