server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    com.netflix: DEBUG
#zuul:
#  routes:
#    microservice-provider:
#      path: /user/**
#      strip-prefix: false
