server:
  port: 8084

dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos

spring:
  application:
    name: dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
