server:
  port: 8081
spring:
  application:
    # 指定注册到Nacos server或者eureka server上的服务名称
    name: spring-cloud-alibaba-consumer-ribbon
  cloud:
    nacos:
      discovery:
        ip: 127.0.0.1
        server-addr: 127.0.0.1:8848
        log-name: spring-cloud-alibaba-consumer-ribbon.log
        username: nacos
        password: nacos

# 配置信息 查看
# https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-discovery
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
