spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - RewritePath=/api/.*?/(?<remaining>.*), /$\{remaining}
      routes:
        - predicates:
            - Path=/api/acct/**
          uri: lb://microservice-provider
        - predicates:
            - Path=/api/sysmanage/**
          uri: lb://buyoffer-sysmanage
        - predicates:
            - Path=/api/email/**
          uri: lb://email