server:
  port: 80

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com:
        cicoding: DEBUG

spring:
  thymeleaf:
    cache: false

