spring:
  application:
    name: microservice-discovery-eureka-ha #服务的名字
server:
  port: 9001
eureka:
  instance:
    hostname: peer3                             # 指定当profile=peer1时，主机名是peer1
  client:
    serviceUrl:
      defaultZone: http://peer1:9002/eureka/,http://peer2:9003/eureka/      # 将自己注册到peer1,peer2这个Eureka上面去
    fetch-registry: true
    register-with-eureka: true
