spring:
  application:
    name: microservice-discovery-eureka-ha #服务的名字
server:
  port: 9001
eureka:
  instance:
    hostname: peer1                               # 指定当profile=peer1时，主机名是peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:9002/eureka/,http://peer3:9003/eureka/      # 将自己注册到peer2,peer3这个Eureka上面去
    fetch-registry: true
    register-with-eureka: true
