server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://10.254.193.190:8761/eureka/
logging:
  level:
    com.netflix: DEBUG
zuul:
  routes:
    systemmanage:
      path: /buyoffer-sysmanage/**
      url: http://localhost:8092/
  sensitive-headers:
#https://www.cnblogs.com/liaojie970/p/9158991.html