brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
brokerIP1 = rocketmq-broker
namesrvAddr = rocketmq-nameserver:9876
defaultTopicQueueNums = 4
autoCreateTopicEnable = true
autoCreateSubscriptionGroup = true
listenPort = 10911
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
storePathRootDir = /home/rocketmq/store
storePathCommitLog = /home/rocketmq/store/commitlog
