version: '3.1'  # 与镜像有关，这里只支持3.1
services:
  mongo:  # 会自动从Docker Hub上自动获取mongo这个镜像
    image: mongo
    restart: always
    ports:
      - 27017:27017  # 本地端口(可自定义):容器内默认端口(mongo设定为27017)
    volumes:
      - ./setup:/docker-entrypoint-initdb.d/  # 本地文件路径:容器内映射路径
    environment:  # admin账号和密码
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: DoNotPeek
  # 如果不需要MongoDB的网页端，以下内容可以不加
  mongo-express:  # 会自动从Docker Hub上自动获取mongo-express这个镜像
    image: mongo-express
    restart: always
    ports:
      - 8080:8081  # 本地端口(可自定义):容器内默认端口(mongo-express设定为8080)
    environment:  # 这里只能使用与上方MONGO_INITDB_ROOT_USERNAME相同的root账号
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: DoNotPeek

  auth-db-mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=auth_db

  movie-db-mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=movie_db