server:
  port: 8788
spring:
  application:
    name: spring-boot-admin
  profiles:
    active:
      - secure
  boot:
    admin:
      ui:
        title: spring-boot-admin-server
      notify:
        mail:
          from: 210006540@qq.com
          to: 427800787@qq.com
  mail:
    host: smtp.qq.com
    username: 210006540@qq.com
    password: umgrwyxkenhabjgc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
# tag::configuration-eureka[]
eureka:   #<1>
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
    hostname: 10.254.193.88
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:8888/eureka/
      defaultZone: http://10.254.193.199:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'  #<2>
  endpoint:
    health:
      show-details: ALWAYS
# end::configuration-eureka[]

---
spring:
  profiles: insecure

---
spring:
  profiles: secure
  security:
    user:
      name: "admin"
      password: "admin"
eureka:
  instance:
    metadata-map:
      user.name: "admin"           # These two are needed so that the server
      user.password: "admin"   # can access the protected client endpoints
